### ISSUE TITLE
new attribute step size?

### ISSUE THREAD

**Issue by prazjain** [milosmns/actual-number-picker#10]
Hi @milosmns,
Is it possible to add a step size attribute, so when I set min to 0 and max to 100, and set step size to 5, then numbers 5,10,15,20... etc are selected, rather than all numbers from 0 to 100.

Thanks

**Comment by milosmns** [comment]
Will look into it Tomorrow. Thanks for the feedback

**Comment by milosmns** [comment]
Ok, so I think it might be weird to output something that is not reflecting the UI. I mean, outputting e.g. 0, 5, 10, 15, etc. and visually displaying everything in between would be confusing to me. Can you do it on your side? For example, when an event comes in, round it to closest 5 mark and then react to that. Does that sound feasible?
