### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by AerWyn81** [milosmns/actual-number-picker#13]
Hi,

When I tried to sync `compile 'me.angrybyte.picker:picker:1.3.1'` on my project, I got these errors :

![screenshot 11-02-2017 13-57-41](https://cloud.githubusercontent.com/assets/22222045/22853908/17cb8688-f062-11e6-86ef-09885f191fd1.png)

Linked here :
![screenshot 11-02-2017 14-04-20](https://cloud.githubusercontent.com/assets/22222045/22853952/1170e94e-f063-11e6-843f-37a1b19b297f.png)

This is my configuration :
![screenshot 11-02-2017 13-58-40](https://cloud.githubusercontent.com/assets/22222045/22853917/3ec937c6-f062-11e6-9759-1b6b903cf499.png)

If you need further information, please ask me,
Sorry for my broken english,

AerWyn81.

**Comment by milosmns** [comment]
Can you check the demo project and compare? I don't think your error is related to the picker code.
Here is the demo project: https://github.com/milosmns/actual-number-picker/tree/master/demo
Demo compiles for me without any issues.

**Comment by AerWyn81** [comment]
Thank you for your quick reply :)

I tried to change this thing I saw different: 
`minSdkVersion 22` by `minSdkVersion 11`
but I still have the same problem. 
Or the `compileSdkVersion 25` and `targetSdkVersion 25` required API 25 to work? I'm on 23 here.

My code without `compile 'me.angrybyte.picker:picker:1.3.1',` works. Any other idea ? I agree, I'm not an expert in android development, so.. that's maybe my fault, but I don't see where I did a mistake. I assume the problem is maybe in the **build.gradle** ? But where..

**Comment by milosmns** [comment]
Wait, how come you don't have the 'dependencies' block in your app gradle file?

**Comment by AerWyn81** [comment]
Yes I have ! I have take only a part of my **build.gradle** before, sorry!

![screenshot 11-02-2017 15-27-42](https://cloud.githubusercontent.com/assets/22222045/22854425/ad8eeeec-f06e-11e6-8c92-1fc28072a958.png)

**Comment by milosmns** [comment]
Ah. Ok can you try to change the appcompat version to `compile 'com.android.support:appcompat-v7:25.1.0'`?
Maybe that's the issue. I don't think we actually use anything from appcompat, not sure why I imported that in the first place. But lets try that first - change the appcompat version and let me know how it goes. 

You might be forced to change your build tools version to the same number (25), Studio will notify you if that is needed.

**Comment by AerWyn81** [comment]
Ah !!! That was the problem !! This now compiles and displays the number picker well. 
Thank you very much and sorry for the stupid mistake !

**Comment by milosmns** [comment]
Not your mistake :) I probably don't need that dependency anyway. Glad this helped.
