### ISSUE TITLE
duplicate values in values.xml

### ISSUE THREAD

**Issue by rickAllDev** [milosmns/actual-number-picker#17]
Had a couple of duplicate definitions when I tried to include your numberpicker library (min_value, max_value and bar_color). Haven't messed around with libraries much.  Can you give me some idea on how what I could modify to solve the problem?

**Comment by milosmns** [comment]
So if you have 'duplicate definitions', you either included the library twice somehow; or you might have the source included in your project and also declared a gradle dependency, which could create a problem.
Other than that, each View has it's own namespace, and its attribute names shouldn't collide with other attribute names. 

Did you check out the demo app? https://github.com/milosmns/actual-number-picker/tree/master/demo
You can compare yours with that one and see what's different.

**Comment by rickAllDev** [comment]
thanks for getting back so quick. don't have it included twice, all I have done is added compile 'me.angrybyte.picker:picker:1.3.1' to module gradle. I am playing around with another library (CrystalRangeSeekbar). These variables are also used there which is causing the conflict.

I don't have any experience with libraries. I assumed there was some mechanism to keep variables localized but no clue on what to look at

**Comment by milosmns** [comment]
That's weird. I think they are mapped to a particular view, so you won't
get a conflict. I haven't experienced that error before... can you try them
out separately and see what's happening? Make sure you include them in your
module's build.gradle, not the root build.gradle. I'm traveling so I might
be slow to respond.

**Comment by milosmns** [comment]
Attributes from my lib are prefixed with the View's name, following up with an underscore, so
`ActualNumberPicker_attribute` so that can't collide with anything. Pls check your XML/Java to see if you have another spot in the code that might be causing the issue, or just start a new project and add things one by one until it breaks :)

**Comment by milosmns** [comment]
Btw, the range bar you're using is definitely causing the issue,

```xml
<attr name="min_value" format="float" />
<attr name="max_value" format="float" />
```

So it's probably best if you ask them to remove those unbound attributes altogether. I can't see a use case for unbound attributes such as these.
