### ISSUE TITLE
How to discern how a value change is made

### ISSUE THREAD

**Issue by Tesvia** [milosmns/actual-number-picker#2]
Hi,
inside the onValueChanged(int oldValue, int newValue), is there a way to discern if a change to the value has been made by "touching" the number picker o by the line code numberPicker.setValue(value)?

I don't know if this is the best solution, but I used the numberPicker.setOnTouchListener() to change the value of a boolen variable, so that I can know when the user touch the picker and so the value will be changed in that way.

Thanks

**Comment by milosmns** [comment]
Hi, 

Didn't really bundle that in. Maybe that's something you can make? Fork and we can discuss further on the pull request

**Comment by Tesvia** [comment]
I found a solution, illustrated in the issue. It works.

**Comment by milosmns** [comment]
Understood :) I just thought it would be good to have in the component itself. Since I'm very busy right now, if you're interested you could add the functionality yourself. But if your solution works well for you, then we maybe don't want to touch anything.
