### ISSUE TITLE
Let max and min range be set programmatically

### ISSUE THREAD

**Issue by ahmadalibaloch** [milosmns/actual-number-picker#6]
I can't access the setters for maximum and minimum range.

**Comment by LunevNF** [comment]
Oh, man. How long we must wait for update? I really needs method setMinValue. Can you add this method to 1.3.0 today? Very need =( After starting my project, I will donate!

**Comment by LunevNF** [comment]
Отблагодарю с размахом всей души русской! :)

**Comment by milosmns** [comment]
For 1.3.0 hardly, as it's already been released :)
Can you pull the source and add it yourself locally (as a temporary workaround)?

Btw, this is a community project, no need for donating :) - you can contribute by engaging with the community, forking, fixing issues, adding new enhancements such as this one. I can probably push it to Maven in one work day if you have a working pull request.

**Comment by LunevNF** [comment]
Unfortunately, in this way I can't add it locally. If it's not difficult, please update library in Maven. =)

**Comment by mathias21** [comment]
Hi @nikitoSha 

Why is that not possible to add it locally? Maybe I can give you a hand in there. I truly believe @milosmns will work much faster if you make a PR with the changes ;)

**Comment by milosmns** [comment]
Yup. If you have a working pull request, I can push to Maven fairly quickly. Pulling in source should also be simple enough, pls try that too.

**Comment by LunevNF** [comment]
Hi, @mathias21 
Oh, my friends. My spoken English is not so good and I find it difficult to understand some expressions. I don't  know how to "Pull in source". 🤣 
In fact, I can only configure build.Gradle or can add a library and connect it from the folder "libs". Today I have tried to download the current version of the library (zip), I took out "Picker" folder - put in the "libs" and tried to connect through build.gradle and build.settings - there were mistakes, "default folder is not found" =)

**Comment by mathias21** [comment]
Hi @nikitoSha 

You are starting a project so you might want to learn about this as well ;)

First, fork this project in Github:
https://help.github.com/articles/fork-a-repo/

Then you will have your own version of the repo, and so you can checkout the code (I would recommend you SourceTree for that):
https://confluence.atlassian.com/sourcetreekb/commit-push-and-pull-a-repository-on-sourcetree-785616067.html

Open it in Android Studio and make your changes. Once you have your methods added, you need to run the Gradle task [assemble]. This will generate the .aar file in folder ./build/outputs/aar/[libraryname].
* If you find an error running assemble, try to change android maven plugin version in main build.gradle to "classpath 'com.github.dcendents:android-maven-gradle-plugin:1.4.1" *

Once you have the .aar, you can paste it in your .gradle folder in your user to test it or use maven local to publish it locally.

Do your testing and once you are sure everything is fine, commit and push to your repo fork. Then make a Pull Request to the main project from @milosmns 

I hope this helps!

**Comment by LunevNF** [comment]
Thanks, I will try to do it now!

**Comment by mathias21** [comment]
It looks like I've found out myself wanting this to happen now. @milosmns I will try to make a PR with this.

**Comment by milosmns** [comment]
Okay, we can comment on the PR when you're done. Thanks for participating :)

**Comment by mathias21** [comment]
> @milosmns question: did you push changes for version 1.3 to remote? I'm fetching and I get nothing. Don't want to commit without latest changes.
My bad, nevermind.

**Comment by mathias21** [comment]
PR made containing this functionality. @ahmadalibaloch @nikitoSha 
https://github.com/milosmns/actual-number-picker/pull/12

**Comment by milosmns** [comment]
Will look into it tomorrow morning 👍

**Comment by milosmns** [comment]
Released in 1.3.1 version, last commit was 03a4fbf
