### ISSUE TITLE
Doesn't showing on Android 6.0 if on ListView

### ISSUE THREAD

**Issue by antoniocgrande** [milosmns/actual-number-picker#7]
I did make one ListView and inflated the ActualNumberPicker on Adapter. Did works fine on Android 4.1.2, but on Android 6.0 doesn't is shown nothing.

**Comment by milosmns** [comment]
You put the slider into a ListView as an item? It should be similar to the ViewPager in terms of touch handling, but a weird case altogether. Can you verify it happens only on 6.0 devices? I have devices with 6.0 and 7.0 and it works fine in a ViewPager - it doesn't do anything special related to a lower API level so this bug doesn't really make sense to me. 

Can you try it with a RecyclerView? https://developer.android.com/training/material/lists-cards.html

**Comment by antoniocgrande** [comment]
Yes, I put the slider into a ListView as an item.
I received the following error log on Android Monitor.

11-30 11:30:30.645 2971-2971/br.com.jcr.icar W/View:
ActualNumberPicker not displayed because it is too large to fit into a
software layer (or drawing cache), needs 780300 bytes, only 384000
available

I'm testing on Android 6.0 emulator.
In my device Android 4.1.2 works fine.

thanks for your help.
regards.



2016-11-24 13:02 GMT-02:00 Milos Marinkovic <notifications@github.com>:

**Comment by milosmns** [comment]
Okay I think it's either the emulator or the ListView (probably emulator due to low memory footprint. You should be using the RecyclerView anyway as ListView is practically deprecated now - more information at https://developer.android.com/training/material/lists-cards.html
